# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get yarn cache dir
        id: yarnCache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarnCache.outputs.dir }}
          key: ${{ runner.os }}-build-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Testing
        run: |
          yarn lint
          yarn test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}

  integrationTest:
    needs: unitTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.18.0
          - 18.x
          - 20.9.0
          - 20.x
          - 22.0.0
          - 22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get yarn cache dir
        id: yarnCache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarnCache.outputs.dir }}
          key: ${{ runner.os }}-build-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Install Node.js ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the test dependencies
        working-directory: integration-test
        run: yarn
      - name: Test
        working-directory: integration-test
        run: yarn eslint src/sample.ts --debug
