name: Patch

on: workflow_dispatch

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - uses: fregante/setup-git-user@v2
      - run: pnpm version patch
      - run: git push
      - run: git push --tags
